/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package open.kotlin
import log4kt.log

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    log.d(App().greeting)
}
